## Parte 1: Creación y manipulación de arrays

### 1.1 Crear un array
Crea un array de 10 elementos enteros aleatorios entre 1 y 100. Imprime el array generado.

In [2]:
import numpy as np
array = np.random.randint(1, 101, size=10)
print("Array original:", array)


Array original: [92 17  7 30 27 21 39 49 43 65]


En esta primera sección, se utiliza la función `np.random.randint` para generar un array de 10 números enteros aleatorios entre 1 y 100. La función recibe como parámetros el rango y el tamaño del array.

### 1.2 Reshape
A partir del array anterior, convierte este array en una matriz de 2x5.

In [4]:
matriz = array.reshape(2, 5)
print("\nMatriz 2x5:\n", matriz)


Matriz 2x5:
 [[92 17  7 30 27]
 [21 39 49 43 65]]


Para convertir el array en una matriz de 2 filas y 5 columnas, se utiliza la función `reshape`. El número total de elementos debe coincidir con el tamaño original del array, por lo que el tamaño resultante es 2x5.

### 1.3 Indexación y slicing
De la matriz obtenida, extrae la primera fila y la última columna. Imprime ambos resultados por separado.

In [5]:
primera_fila = matriz[0, :]
print("\nPrimera fila:", primera_fila)

ultima_columna = matriz[:, -1]
print("Última columna:", ultima_columna)


Primera fila: [92 17  7 30 27]
Última columna: [27 65]


Utilizamos indexación para extraer la primera fila (`matriz[0, :]`) y la última columna (`matriz[:, -1]`). En NumPy, el operador `:` significa "todas las filas" o "todas las columnas", dependiendo de su posición.

### 1.4 Modificación
Cambia el valor de los elementos en la segunda fila a ceros.

In [13]:
matriz[1, :] = 0
print("\nSegunda fila modificada:\n", matriz)


Segunda fila modificada:
 [[92 17  7 30 27]
 [ 0  0  0  0  0]]


Aquí, modificamos todos los elementos de la segunda fila de la matriz para que sean ceros. Esto se hace mediante indexación asignando el valor `0` a toda la fila con `matriz[1, :] = 0`.

## Parte 2: Operaciones básicas con NumPy

### 2.1 Operaciones aritméticas

- Crea dos arrays de 5 elementos enteros aleatorios entre 1 y 50.
- Suma ambos arrays y luego multiplícalos entre sí.
- Calcula el promedio y la desviación estándar de los resultados obtenidos.

In [14]:
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)
print("\nArray 1:", array1)
print("Array 2:", array2)

suma = array1 + array2
print("\nSuma de los arrays:", suma)

multiplicacion = array1 * array2
print("Multiplicación de los arrays:", multiplicacion)

promedio_suma = np.mean(suma)
desviacion_suma = np.std(suma)
promedio_mult = np.mean(multiplicacion)
desviacion_mult = np.std(multiplicacion)

print("\nPromedio de la suma:", promedio_suma)
print("Desviación estándar de la suma:", desviacion_suma)
print("Promedio de la multiplicación:", promedio_mult)
print("Desviación estándar de la multiplicación:", desviacion_mult)



Array 1: [16  3 22  2 35]
Array 2: [18 27 49  8 48]

Suma de los arrays: [34 30 71 10 83]
Multiplicación de los arrays: [ 288   81 1078   16 1680]

Promedio de la suma: 45.6
Desviación estándar de la suma: 27.163210414087654
Promedio de la multiplicación: 628.6
Desviación estándar de la multiplicación: 647.8510940023178


En esta sección, generamos dos arrays aleatorios de 5 elementos con valores entre 1 y 50. Luego, sumamos y multiplicamos los arrays elemento por elemento. Finalmente, utilizamos las funciones `mean()` y `std()` de NumPy para calcular el promedio y la desviación estándar de los resultados.

### 2.2 Condiciones lógicas
Genera un array de 20 números aleatorios entre 0 y 1. Usa condiciones lógicas para:

- Reemplazar los valores menores a 0.5 con 0.
- Reemplazar los valores mayores o iguales a 0.5 con 1.

In [15]:
array_random = np.random.rand(20)
print("\nArray aleatorio original:\n", array_random)

array_random[array_random < 0.5] = 0

array_random[array_random >= 0.5] = 1

print("\nArray modificado con condiciones lógicas:\n", array_random)



Array aleatorio original:
 [0.13342073 0.82946975 0.64945467 0.89005812 0.04478245 0.08040803
 0.61860107 0.46222078 0.39033566 0.5240669  0.68492319 0.83105798
 0.02476276 0.35910225 0.90601459 0.12093813 0.22147193 0.57779471
 0.28756288 0.43522835]

Array modificado con condiciones lógicas:
 [0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.]


Aquí, generamos un array de 20 números aleatorios entre 0 y 1 utilizando `np.random.rand()`. Luego aplicamos condiciones lógicas: los valores menores a 0.5 son reemplazados por `0`, y los valores iguales o mayores a 0.5 por `1`. 

### 2.3 Producto escalar
Crea dos arrays de tamaño 3x3. Calcula el producto escalar entre ambos.

In [16]:
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz2 = np.random.randint(1, 10, size=(3, 3))

print("\nMatriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)

producto_escalar = np.dot(matriz1, matriz2)
print("\nProducto escalar entre las matrices:\n", producto_escalar)


Matriz 1:
 [[7 9 6]
 [9 8 4]
 [9 8 9]]
Matriz 2:
 [[6 5 9]
 [5 9 1]
 [7 9 8]]

Producto escalar entre las matrices:
 [[129 170 120]
 [122 153 121]
 [157 198 161]]


Creamos dos matrices de tamaño 3x3 y calculamos el producto escalar entre ellas utilizando la función `np.dot()`.

## Parte 3: Análisis de datos con NumPy

### 3.1 Matriz de datos
Crea una matriz de 5 filas y 4 columnas que contenga datos aleatorios entre 1 y 20. Cada fila representa a una persona, y cada columna representa una medición diferente (como altura, peso, edad, presión arterial).

In [17]:
datos = np.random.randint(1, 21, size=(5, 4))
print("\nMatriz de datos (personas vs mediciones):\n", datos)


Matriz de datos (personas vs mediciones):
 [[10 18  8 17]
 [10 15  9 10]
 [14 20 18  5]
 [ 4 14 16  4]
 [13 11 20 16]]


Creamos una matriz de 5 filas y 4 columnas donde cada fila representa a una persona y cada columna una medición. Los valores son generados aleatoriamente entre 1 y 20.

### 3.2 Estadísticas
- Calcula la media de cada columna (medición).
- Encuentra el valor máximo y mínimo de cada fila.
- Ordena las filas según los valores de la segunda columna (peso).

In [19]:
media_columnas = np.mean(datos, axis=0)
print("\nMedia de cada columna:", media_columnas)

max_filas = np.max(datos, axis=1)
min_filas = np.min(datos, axis=1)

print("Máximo de cada fila:", max_filas)
print("Mínimo de cada fila:", min_filas)

datos_ordenados = datos[datos[:, 1].argsort()]
print("\nMatriz ordenada por la segunda columna (peso):\n", datos_ordenados)


Media de cada columna: [10.2 15.6 14.2 10.4]
Máximo de cada fila: [18 15 20 16 20]
Mínimo de cada fila: [ 8  9  5  4 11]

Matriz ordenada por la segunda columna (peso):
 [[13 11 20 16]
 [ 4 14 16  4]
 [10 15  9 10]
 [10 18  8 17]
 [14 20 18  5]]


Primero, calculamos la media de cada columna utilizando `np.mean()`. Luego, encontramos el valor máximo y mínimo de cada fila con `np.max()` y `np.min()`. Finalmente, ordenamos las filas de la matriz de acuerdo con los valores de la segunda columna usando `argsort()`.